#!/bin/sh

# Copyright 2020 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

program=$0
[ -h "$program" ] && PRG=$(readlink -f "$program")
program_dir=$(dirname "$program")

[ -z "$PANDORA_HOME" ] && PANDORA_HOME=$(cd "$program_dir/.." > /dev/null; pwd)

if [ -z "$JAVA_HOME" ]
then
    java_cmd=$(which java)
else
    java_cmd="$JAVA_HOME/bin/java"
fi

module=org.leadpony.pandora/org.leadpony.pandora.Launcher
exec "$java_cmd" -p "$PANDORA_HOME/lib" -m $module "$@"
